bic.get.colors <- function(numClrs, sort = FALSE){

    aClrs <- c("green4","hotpink","gold","mediumorchid3", "mediumturquoise",
               "yellowgreen", "royalblue3", "violetred3", "chocolate2",
               "plum", "deepskyblue1")

    clrsDist <- c("#7e8c76", "hotpink", "gold3", "steelblue3",
                  "gold", "burlywood1", "#a1788d", "mediumturquoise",
                  "#fcba03", "turquoise4", "lightpink1", "royalblue3",
                  "plum", "firebrick2", "green4", "slategray1",
                  "chocolate2", "mediumorchid3", "royalblue4", "yellowgreen",
                  "lightsalmon", "#c4c2c3", "deepskyblue1", "violetred3")

    clrsGradient <- c("firebrick2", "chocolate2", "#fcba03", "lightsalmon",
                      "burlywood1", "gold", "gold3", "#7e8c76",
                      "turquoise4", "green4", "yellowgreen", "mediumturquoise",
                      "royalblue4", "royalblue3", "steelblue3", "deepskyblue1",
                      "slategray1", "#a1788d", "mediumorchid3", "plum",
                      "violetred3", "hotpink", "lightpink1", "#c4c2c3")

    lens <- list(a = length(aClrs), dist = length(clrsDist), grad = length(clrsGradient))
    idxs <- seq(numClrs)

    if(numClrs > max(unlist(lens))){
        ## return the uglier, but larger palette
        if(sort){ log_warn("Color sorting is not supported when using >", max(unlist(lens)), " colors.") }
        return(c48[idxs])
    }
    if(numClrs <= lens$a){
        if(sort){
            return(clrsGradient[clrsGradient %in% aClrs][idxs])
        }
        return(aClrs[idxs])
    }
    if(sort){
        return(clrsGradient[idxs])
    }
    return(clrsDist[idxs])
}




#' Extract a legend from a gplot
#' 
#' Extract a legend from a plot generated with ggplot
#' 
#' @param plt    a plot generated with ggplot 
getLegend <- function(plt){
    tmp <- tryCatch({
               ggplot_gtable(ggplot_build(plt))
             }, error=function(e){
               plt
             })
    leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
    legend <- tmp$grobs[[leg]]
    return(legend)
}

#' Get legend from a gplot
#' 
#' Given a plot generated with ggplot(), separate and return only
#' the legend component
#' 
#' @param a.gplot  a plot generated by ggplot()
#' @return  the legend of a.gplot 
g_legend <- getLegend


#' Remove a legend from a gplot
#' 
#' Remove a legend from a gplot
#'
#' @param plt    a plot generated with ggplot 
removeLegend <- function(plt){
    tmp <- ggplot_gtable(ggplot_build(plt))
    leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
    tmp$grobs[[leg]] <- NULL
    return(tmp)
}

